[build]
  base = "."
  publish = "./build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]

[[headers]]
  for = "/*.otf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-otf"